title: The Language of Lagomorphs
description: Your Guide to Rabbit Communication

strict_front_matter: true
kramdown:
  auto_ids: true
permalink: /:basename

defaults:
  - scope:
      path: ""
    values:
      sidebar:
        nav: nav
      layout: default

ignore:
  - README.md
  - CONTRIBUTING.md
